### ISSUE TITLE
 public expandedRow = CustomRowComponent;

### ISSUE THREAD

**Issue by sante85** [hjalmers/angular2-generic-table#17]
public expandedRow = CustomRowComponent;
not passed to let factory = this.componentFactoryResolver.resolveComponentFactory(this.type);

class GtExpandingRowComponent
this.type is undefined
this.row is correctely valued

in app.module i have defined
import module and entryComponents: [ CustomRowComponent ],

**Comment by hjalmers** [comment]
What's your markup for the component that uses generic table? Sounds like you might be forgetting to pass the custom row component to your table.
