### ISSUE TITLE
Search term highlighting when using lazy loading

### ISSUE THREAD

**Issue by rw-s** [hjalmers/angular2-generic-table#30]
It would be useful if we could use a function similar to (or the same one) "gtSearch" to highlight search matches where the search was done on the server side.

Our internal issue ID: 194

**Comment by hjalmers** [comment]
See updated example  [here](https://hjalmers.github.io/angular2-generic-table/examples) on how you can implement it using gtSearch function.

Basically you'll need to enable highlight `[gtHighlightSearch]="true"` and use the gtSearch function to set the search term(s) you want to highlight. Note that you must declare the table as a view child like this: 
``` 
@ViewChild(GenericTableComponent)
private myTable: GenericTableComponent<any, CustomRowComponent>;
```

Then you'll be able to use the function if you add a local variable to the table.

You can also disable highlighting for a column by adding `search:false` to column settings object.

**Comment by rw-s** [comment]
Looks good!
