### ISSUE TITLE
Ability to disable caching of data within the table

### ISSUE THREAD

**Issue by rw-s** [hjalmers/angular2-generic-table#31]
A config option that would make the table not cache data internally. It would cause a paging event always, so we have the opportunity to load the latest data from the server.

Our internal issue ID: 192

**Comment by hjalmers** [comment]
It should definitely be a setting to turn caching off but you can always change the event you're listening too as well. If you listen for `gt-page-changed` instead of `gt-page-changed-lazy`, the table will always request new data.

**Comment by rw-s** [comment]
I see that, however it'll display the cached data while we are requesting data in response to `gt-page-changed`.
