### ISSUE TITLE
AOT Build Error

### ISSUE THREAD

**Issue by Shankulkarni** [hjalmers/angular2-generic-table#49]
When I am trying to build my app in aot, its giving me error in angular2-generic-table::

 TS2314: Generic type 'GenericTableComponent<R, C>' requires 2 type argument(s).

<img width="1280" alt="screen shot 2017-02-22 at 7 59 11 am" src="https://cloud.githubusercontent.com/assets/11802742/23194714/cab7eb08-f8d5-11e6-8826-80b577df787a.png">

**Comment by hjalmers** [comment]
Hi and sorry for the late reply, my guess is that you've missed passing arguments when declaring your table ie. you should use:

```private myTable: GenericTableComponent<any, any>; ```

Unless you know the specific types, first argument is the type/interface for your row while the second one refers to the component you're trying to display when expanding a row.

**Comment by harryy2510** [comment]
<img width="1203" alt="screen shot 2017-03-05 at 12 40 16 pm" src="https://cloud.githubusercontent.com/assets/7416971/23585296/f5560722-01a0-11e7-985c-1cba64e3975e.png">


We did the same brother. It is still giving same errors while building with AOT.

Typescript version: 2.2.0
Angular2 version: 2.4.5

**Comment by Shankulkarni** [comment]
@hjalmers 
have you tried building the project in aot ?  Does it works?

**Comment by hjalmers** [comment]
@Shankulkarni yes it works for me using angular-cli, are you using angular-seed or which project have you used for your projects? I'll try and see if I can reproduce somehow. I guess its working for you without AOT?

**Comment by harryy2510** [comment]
@hjalmers 
Me and shan tried it with our own setup using webpack.
Yes it is working without AOT but we are getting same error with AOT.

**Comment by harryy2510** [comment]
@hjalmers 
Can we discuss this on skype or any other platform?
We wont be able to explain our project here and since we made the whole project using your table, it is too urgent for us.

**Comment by hjalmers** [comment]
Sure add me on skype (same username as GitHub username)

**Comment by Shankulkarni** [comment]
It finally worked, the problem was in our aot configurations. 
@hjalmers Thank you!!

**Comment by hjalmers** [comment]
No problem, glad to hear you got it working:)
